UCLA scl 1.0
# Created    :   Wed Dec 18 17:45:40 2019
# User       :   Generated .scl File for ICCAD2015 Contest

NumRows : 902

CoreRow Horizontal
  Coordinate    :     10
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     22
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     34
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     46
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     58
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     70
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     82
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     94
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     106
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     118
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     130
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     142
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     154
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     166
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     178
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     190
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     202
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     214
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     226
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     238
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     250
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     262
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     274
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     286
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     298
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     310
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     322
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     334
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     346
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     358
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     370
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     382
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     394
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     406
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     418
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     430
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     442
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     454
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     466
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     478
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     490
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     502
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     514
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     526
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     538
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     550
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     562
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     574
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     586
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     598
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     610
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     622
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     634
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     646
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     658
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     670
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     682
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     694
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     706
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     718
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     730
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     742
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     754
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     766
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     778
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     790
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     802
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     814
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     826
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     838
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     850
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     862
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     874
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     886
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     898
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     910
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     922
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     934
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     946
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     958
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     970
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     982
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     994
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1006
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1018
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1030
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1042
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1054
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1066
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1078
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1090
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1102
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1114
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1126
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1138
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1150
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1162
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1174
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1186
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1198
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1210
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1222
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1234
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1246
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1258
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1270
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1282
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1294
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1306
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1318
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1330
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1342
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1354
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1366
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1378
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1390
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1402
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1414
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1426
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1438
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1450
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1462
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1474
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1486
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1498
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1510
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1522
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1534
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1546
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1558
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1570
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1582
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1594
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1606
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1618
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1630
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1642
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1654
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1666
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1678
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1690
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1702
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1714
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1726
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1738
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1750
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1762
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1774
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1786
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1798
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1810
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1822
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1834
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1846
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1858
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1870
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1882
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1894
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1906
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1918
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1930
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1942
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1954
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1966
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1978
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     1990
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2002
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2014
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2026
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2038
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2050
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2062
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2074
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2086
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2098
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2110
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2122
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2134
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2146
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2158
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2170
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2182
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2194
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2206
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2218
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2230
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2242
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2254
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2266
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2278
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2290
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2302
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2314
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2326
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2338
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2350
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2362
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2374
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2386
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2398
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2410
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2422
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2434
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2446
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2458
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2470
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2482
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2494
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2506
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2518
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2530
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2542
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2554
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2566
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2578
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2590
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2602
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2614
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2626
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2638
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2650
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2662
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2674
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2686
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2698
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2710
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2722
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2734
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2746
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2758
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2770
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2782
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2794
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2806
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2818
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2830
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2842
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2854
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2866
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2878
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2890
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2902
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2914
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2926
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2938
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2950
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2962
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2974
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2986
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     2998
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3010
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3022
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3034
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3046
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3058
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3070
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3082
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3094
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3106
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3118
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3130
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3142
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3154
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3166
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3178
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3190
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3202
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3214
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3226
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3238
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3250
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3262
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3274
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3286
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3298
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3310
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3322
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3334
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3346
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3358
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3370
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3382
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3394
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3406
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3418
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3430
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3442
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3454
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3466
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3478
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3490
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3502
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3514
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3526
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3538
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3550
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3562
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3574
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3586
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3598
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3610
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3622
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3634
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3646
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3658
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3670
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3682
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3694
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3706
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3718
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3730
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3742
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3754
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3766
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3778
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3790
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3802
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3814
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3826
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3838
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3850
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3862
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3874
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3886
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3898
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3910
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3922
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3934
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3946
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3958
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3970
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3982
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     3994
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4006
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4018
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4030
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4042
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4054
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4066
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4078
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4090
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4102
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4114
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4126
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4138
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4150
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4162
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4174
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4186
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4198
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4210
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4222
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4234
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4246
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4258
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4270
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4282
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4294
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4306
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4318
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4330
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4342
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4354
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4366
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4378
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4390
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4402
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4414
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4426
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4438
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4450
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4462
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4474
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4486
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4498
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4510
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4522
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4534
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4546
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4558
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4570
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4582
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4594
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4606
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4618
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4630
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4642
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4654
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4666
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4678
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4690
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4702
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4714
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4726
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4738
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4750
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4762
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4774
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4786
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4798
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4810
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4822
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4834
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4846
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4858
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4870
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4882
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4894
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4906
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4918
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4930
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4942
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4954
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4966
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4978
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     4990
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5002
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5014
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5026
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5038
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5050
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5062
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5074
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5086
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5098
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5110
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5122
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5134
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5146
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5158
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5170
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5182
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5194
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5206
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5218
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5230
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5242
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5254
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5266
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5278
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5290
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5302
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5314
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5326
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5338
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5350
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5362
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5374
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5386
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5398
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5410
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5422
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5434
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5446
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5458
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5470
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5482
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5494
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5506
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5518
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5530
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5542
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5554
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5566
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5578
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5590
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5602
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5614
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5626
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5638
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5650
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5662
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5674
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5686
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5698
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5710
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5722
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5734
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5746
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5758
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5770
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5782
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5794
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5806
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5818
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5830
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5842
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5854
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5866
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5878
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5890
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5902
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5914
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5926
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5938
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5950
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5962
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5974
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5986
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     5998
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6010
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6022
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6034
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6046
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6058
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6070
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6082
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6094
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6106
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6118
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6130
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6142
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6154
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6166
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6178
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6190
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6202
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6214
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6226
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6238
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6250
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6262
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6274
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6286
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6298
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6310
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6322
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6334
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6346
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6358
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6370
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6382
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6394
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6406
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6418
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6430
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6442
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6454
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6466
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6478
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6490
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6502
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6514
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6526
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6538
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6550
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6562
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6574
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6586
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6598
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6610
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6622
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6634
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6646
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6658
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6670
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6682
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6694
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6706
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6718
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6730
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6742
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6754
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6766
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6778
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6790
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6802
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6814
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6826
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6838
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6850
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6862
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6874
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6886
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6898
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6910
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6922
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6934
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6946
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6958
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6970
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6982
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     6994
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7006
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7018
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7030
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7042
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7054
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7066
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7078
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7090
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7102
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7114
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7126
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7138
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7150
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7162
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7174
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7186
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7198
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7210
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7222
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7234
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7246
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7258
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7270
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7282
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7294
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7306
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7318
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7330
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7342
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7354
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7366
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7378
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7390
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7402
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7414
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7426
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7438
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7450
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7462
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7474
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7486
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7498
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7510
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7522
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7534
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7546
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7558
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7570
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7582
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7594
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7606
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7618
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7630
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7642
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7654
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7666
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7678
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7690
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7702
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7714
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7726
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7738
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7750
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7762
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7774
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7786
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7798
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7810
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7822
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7834
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7846
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7858
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7870
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7882
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7894
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7906
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7918
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7930
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7942
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7954
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7966
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7978
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     7990
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8002
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8014
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8026
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8038
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8050
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8062
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8074
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8086
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8098
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8110
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8122
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8134
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8146
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8158
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8170
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8182
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8194
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8206
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8218
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8230
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8242
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8254
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8266
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8278
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8290
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8302
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8314
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8326
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8338
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8350
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8362
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8374
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8386
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8398
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8410
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8422
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8434
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8446
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8458
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8470
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8482
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8494
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8506
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8518
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8530
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8542
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8554
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8566
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8578
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8590
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8602
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8614
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8626
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8638
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8650
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8662
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8674
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8686
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8698
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8710
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8722
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8734
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8746
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8758
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8770
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8782
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8794
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8806
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8818
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8830
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8842
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8854
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8866
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8878
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8890
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8902
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8914
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8926
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8938
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8950
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8962
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8974
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8986
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     8998
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9010
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9022
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9034
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9046
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9058
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9070
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9082
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9094
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9106
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9118
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9130
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9142
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9154
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9166
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9178
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9190
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9202
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9214
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9226
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9238
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9250
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9262
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9274
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9286
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9298
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9310
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9322
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9334
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9346
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9358
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9370
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9382
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9394
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9406
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9418
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9430
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9442
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9454
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9466
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9478
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9490
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9502
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9514
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9526
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9538
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9550
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9562
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9574
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9586
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9598
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9610
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9622
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9634
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9646
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9658
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9670
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9682
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9694
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9706
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9718
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9730
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9742
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9754
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9766
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9778
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9790
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9802
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9814
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9826
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9838
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9850
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9862
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9874
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9886
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9898
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9910
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9922
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9934
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9946
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9958
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9970
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9982
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     9994
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10006
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10018
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10030
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10042
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10054
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10066
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10078
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10090
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10102
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10114
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10126
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10138
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10150
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10162
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10174
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10186
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10198
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10210
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10222
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10234
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10246
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10258
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10270
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10282
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10294
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10306
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10318
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10330
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10342
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10354
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10366
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10378
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10390
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10402
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10414
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10426
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10438
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10450
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10462
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10474
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10486
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10498
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10510
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10522
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10534
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10546
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10558
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10570
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10582
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10594
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10606
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10618
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10630
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10642
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10654
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10666
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10678
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10690
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10702
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10714
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10726
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10738
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10750
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10762
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10774
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10786
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10798
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10810
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
CoreRow Horizontal
  Coordinate    :     10822
  Height        :     12
  Sitewidth     :     1
  Sitespacing   :     1
  Siteorient    :     1
  Sitesymmetry  :     1
  SubrowOrigin  :     10    NumSites  :  10543
END
